Create quantmod_translation.Rmd
jtr13/cc21 pull request #42
Opened 2021-03-21 20:09 UTC by jx2428

# CC from Jiashu (Jerry) Xia

2021-03-25 19:28 UTC, yosha-tomar requested changes
Please make the following changes:
1. Completely remove the YAML header and use the following format:

    # TITLE
 
    Your Name

     Your content

For reference see the sample file: https://github.com/jtr13/cc21/blob/main/sample_project.Rmd
And the second point of section 2.2 in:
https://jtr13.github.io/cc21/github-submission-instructions.html#preparing-your-.rmd-file

2. Remove setup label from line 16.
For reference see point 6 of section 2.2 in:
https://jtr13.github.io/cc21/github-submission-instructions.html#preparing-your-.rmd-file

2021-03-31 15:38 UTC, yosha-tomar requested changes
Thanks for the changes. Please write the title in the correct format. It should begin with a single hashtag followed by a space and then your title.

2021-03-31 15:38 UTC, yosha-tomar commented on quantmod_translation.Rmd
> +R Quantmod Package Tutorial & Translation
Change Title to "# R Quantmod Package Tutorial & Translation"

2021-03-31 23:53 UTC, yosha-tomar commented
Thank you for your contribution!

2021-03-31 23:53 UTC, merged

2021-04-01 00:07 UTC, shauryamalik commented
I see the build failed for this merge: https://github.com/jtr13/cc21/runs/2241670443 @yosha-tomar

2021-04-01 00:16 UTC, yosha-tomar commented
I'm working on it. 
The Rmd file had some characters which were creating the issue.