updated as suggested
jtr13/cc21 pull request #96
Opened 2021-04-02 00:51 UTC by brianwmao

updated as suggested

2021-04-02 19:26 UTC, shauryamalik requested changes

2021-04-02 19:26 UTC, shauryamalik commented on cc_dv_bm3024.Rmd
> +```{r setup, include=FALSE}
Please follow 2.2.6 (https://jtr13.github.io/cc21/github-submission-instructions.html) and remove 'setup'

2021-04-02 19:26 UTC, shauryamalik commented on cc_dv_bm3024.Rmd
> +#### Basic Boxplot
On line 61 the heading has 2 hashtags, line 63 must have 3 hashtags for correct ordering.

2021-04-02 19:26 UTC, shauryamalik commented on cc_dv_bm3024.Rmd
> +## 8 Work Cited:
Number is not needed with the hashtags.

2021-04-02 19:27 UTC, shauryamalik commented
There is no need to create a new PR every time you make changes. You can continue to edit these files by committing to the same branch. Furthermore if https://github.com/jtr13/cc21/pull/94 is a duplicate PR please close it.

2021-04-03 23:18 UTC, brianwmao commented
Hi Shaurya,

I am able to do the pull request anymore would you please upload my file
please

please find attached file

Thank,
Brian

On Fri, Apr 2, 2021 at 3:27 PM Shaurya Malik ***@***.***>
wrote:

> There is no need to create a new PR every time you make changes. You can
> continue to edit these files by committing to the same branch. Furthermore
> if #94 <https://github.com/jtr13/cc21/pull/94> is a duplicate PR please
> close it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jtr13/cc21/pull/96#issuecomment-812677029>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASYDMTKIRLDYIT4VWSLGBM3TGYLCJANCNFSM42IA7X4Q>
> .
>

2021-04-03 23:24 UTC, closed without merging